'on':
  push:
    branches:
      - main
name: go-ci
jobs:
  build:
    strategy:
      matrix:
        go-version:
          - 1.13.x
          - 1.14.x
          - 1.15.x
          - 1.16.x
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: '${{ matrix.platform }}'
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '${{ matrix.go-version }}'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Tidy
        run: |
          go mod tidy
      - name: Build
        run: go build cmd/main.go